import 'package:flutter/material.dart';

class LanguageConstants {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'appTitle': 'Good Sort Game',
      'startGame': 'Start Game',
      'level': 'Level',
      'score': 'Score',
      'time': 'Time',
      'gameOver': 'Game Over!',
      'levelComplete': 'Level Complete!',
      'playAgain': 'Play Again',
      'nextLevel': 'Next Level',
      'finalScore': 'Final Score',
      'levelReached': 'Level Reached',
      'timeLeft': 'Time Left',
      'seconds': 'seconds',
      'selectLanguage': 'Select Your Language',
      'chooseLanguage': 'Choose Language',
      'welcome': 'Welcome to Good Sort Game!',
      'subtitle': 'Sort items into their correct categories!',
      'changeLanguage': 'Change Language',
    },
    'zh': {
      'appTitle': '好分类游戏',
      'startGame': '开始游戏',
      'level': '关卡',
      'score': '得分',
      'time': '时间',
      'gameOver': '游戏结束！',
      'levelComplete': '关卡完成！',
      'playAgain': '再玩一次',
      'nextLevel': '下一关',
      'finalScore': '最终得分',
      'levelReached': '达到关卡',
      'timeLeft': '剩余时间',
      'seconds': '秒',
      'selectLanguage': '选择你的语言',
      'chooseLanguage': '选择语言',
      'welcome': '欢迎来到好分类游戏！',
      'subtitle': '将物品分类到正确的类别中！',
      'changeLanguage': '更改语言',
    },
    'vi': {
      'appTitle': 'Trò Chơi Phân Loại',
      'startGame': 'Bắt Đầu Chơi',
      'level': 'Cấp Độ',
      'score': 'Điểm Số',
      'time': 'Thời Gian',
      'gameOver': 'Kết Thúc!',
      'levelComplete': 'Hoàn Thành Cấp Độ!',
      'playAgain': 'Chơi Lại',
      'nextLevel': 'Cấp Độ Tiếp',
      'finalScore': 'Điểm Cuối Cùng',
      'levelReached': 'Đạt Cấp Độ',
      'timeLeft': 'Thời Gian Còn Lại',
      'seconds': 'giây',
      'selectLanguage': 'Chọn Ngôn Ngữ Của Bạn',
      'chooseLanguage': 'Chọn Ngôn Ngữ',
      'welcome': 'Chào Mừng Đến Với Trò Chơi Phân Loại!',
      'subtitle': 'Phân loại các vật phẩm vào đúng danh mục!',
      'changeLanguage': 'Đổi Ngôn Ngữ',
    },
    'ko': {
      'appTitle': '좋은 분류 게임',
      'startGame': '게임 시작',
      'level': '레벨',
      'score': '점수',
      'time': '시간',
      'gameOver': '게임 오버!',
      'levelComplete': '레벨 완료!',
      'playAgain': '다시 플레이',
      'nextLevel': '다음 레벨',
      'finalScore': '최종 점수',
      'levelReached': '도달한 레벨',
      'timeLeft': '남은 시간',
      'seconds': '초',
      'selectLanguage': '언어 선택',
      'chooseLanguage': '언어를 선택하세요',
      'welcome': '좋은 분류 게임에 오신 것을 환영합니다!',
      'subtitle': '아이템을 올바른 카테고리로 분류하세요!',
      'changeLanguage': '언어 변경',
    },
    'es': {
      'appTitle': 'Juego de Clasificación',
      'startGame': 'Comenzar Juego',
      'level': 'Nivel',
      'score': 'Puntuación',
      'time': 'Tiempo',
      'gameOver': '¡Juego Terminado!',
      'levelComplete': '¡Nivel Completado!',
      'playAgain': 'Jugar de Nuevo',
      'nextLevel': 'Siguiente Nivel',
      'finalScore': 'Puntuación Final',
      'levelReached': 'Nivel Alcanzado',
      'timeLeft': 'Tiempo Restante',
      'seconds': 'segundos',
      'selectLanguage': 'Selecciona tu Idioma',
      'chooseLanguage': 'Elegir Idioma',
      'welcome': '¡Bienvenido al Juego de Clasificación!',
      'subtitle': '¡Clasifica los elementos en sus categorías correctas!',
      'changeLanguage': 'Cambiar Idioma',
    },
    'fr': {
      'appTitle': 'Jeu de Tri',
      'startGame': 'Commencer',
      'level': 'Niveau',
      'score': 'Score',
      'time': 'Temps',
      'gameOver': 'Partie Terminée!',
      'levelComplete': 'Niveau Complété!',
      'playAgain': 'Rejouer',
      'nextLevel': 'Niveau Suivant',
      'finalScore': 'Score Final',
      'levelReached': 'Niveau Atteint',
      'timeLeft': 'Temps Restant',
      'seconds': 'secondes',
      'selectLanguage': 'Sélectionnez votre Langue',
      'chooseLanguage': 'Choisir la Langue',
      'welcome': 'Bienvenue au Jeu de Tri!',
      'subtitle': 'Triez les éléments dans leurs catégories correctes!',
      'changeLanguage': 'Changer de Langue',
    },
    'de': {
      'appTitle': 'Sortierspiel',
      'startGame': 'Spiel Starten',
      'level': 'Level',
      'score': 'Punktzahl',
      'time': 'Zeit',
      'gameOver': 'Spiel Beendet!',
      'levelComplete': 'Level Geschafft!',
      'playAgain': 'Erneut Spielen',
      'nextLevel': 'Nächstes Level',
      'finalScore': 'Endpunktzahl',
      'levelReached': 'Erreichtes Level',
      'timeLeft': 'Verbleibende Zeit',
      'seconds': 'Sekunden',
      'selectLanguage': 'Wähle deine Sprache',
      'chooseLanguage': 'Sprache Wählen',
      'welcome': 'Willkommen beim Sortierspiel!',
      'subtitle': 'Sortiere die Gegenstände in die richtigen Kategorien!',
      'changeLanguage': 'Sprache Ändern',
    },
    'ja': {
      'appTitle': '分類ゲーム',
      'startGame': 'ゲーム開始',
      'level': 'レベル',
      'score': 'スコア',
      'time': '時間',
      'gameOver': 'ゲームオーバー！',
      'levelComplete': 'レベルクリア！',
      'playAgain': 'もう一度プレイ',
      'nextLevel': '次のレベル',
      'finalScore': '最終スコア',
      'levelReached': '到達レベル',
      'timeLeft': '残り時間',
      'seconds': '秒',
      'selectLanguage': '言語を選択',
      'chooseLanguage': '言語を選ぶ',
      'welcome': '分類ゲームへようこそ！',
      'subtitle': 'アイテムを正しいカテゴリーに分類しましょう！',
      'changeLanguage': '言語を変更',
    },
    'ru': {
      'appTitle': 'Игра Сортировка',
      'startGame': 'Начать Игру',
      'level': 'Уровень',
      'score': 'Счёт',
      'time': 'Время',
      'gameOver': 'Игра Окончена!',
      'levelComplete': 'Уровень Пройден!',
      'playAgain': 'Играть Снова',
      'nextLevel': 'Следующий Уровень',
      'finalScore': 'Итоговый Счёт',
      'levelReached': 'Достигнутый Уровень',
      'timeLeft': 'Осталось Времени',
      'seconds': 'секунд',
      'selectLanguage': 'Выберите Язык',
      'chooseLanguage': 'Выбор Языка',
      'welcome': 'Добро Пожаловать в Игру Сортировка!',
      'subtitle': 'Сортируйте предметы по правильным категориям!',
      'changeLanguage': 'Сменить Язык',
    },
  };

  static const List<Language> supportedLanguages = [
    Language('en', 'English', Icons.flag),
    Language('zh', '中文', Icons.flag),
    Language('vi', 'Tiếng Việt', Icons.flag),
    Language('ko', '한국어', Icons.flag),
    Language('es', 'Español', Icons.flag),
    Language('fr', 'Français', Icons.flag),
    Language('de', 'Deutsch', Icons.flag),
    Language('ja', '日本語', Icons.flag),
    Language('ru', 'Русский', Icons.flag),
  ];
}

class Language {
  final String code;
  final String name;
  final IconData icon;

  const Language(this.code, this.name, this.icon);
}
